name: Release
on:
  release:
    types: [created]

jobs:

  goreleaser:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    name: goreleaser
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}